
  CREATE TABLE "SCOTT"."TUSER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"CREATEDATETIME" TIMESTAMP (6) DEFAULT systimestamp, 
	"MODIFYDATETIME" TIMESTAMP (6) DEFAULT systimestamp, 
	"NAME" VARCHAR2(20 BYTE), 
	"PWD" VARCHAR2(20 BYTE), 
	"CREATETIME" DATE DEFAULT sysdate, 
	"UPDATETIME" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
 
  CREATE TABLE "SCOTT"."FRIEND" 
   (	"CREATEDATE" VARCHAR2(20 BYTE) DEFAULT to_char(sysdate,'yyyy:mm:dd') NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SEX" VARCHAR2(20 BYTE), 
	"BIRTHDAY" VARCHAR2(20 BYTE) DEFAULT '未知', 
	"TELEPHONE" VARCHAR2(20 BYTE) DEFAULT '未知', 
	"QQ" VARCHAR2(20 BYTE) DEFAULT '未知', 
	"HOBBY" VARCHAR2(100 BYTE) DEFAULT '未知', 
	"SCHOOL" VARCHAR2(100 BYTE) DEFAULT '未知', 
	"EDUCATION_BACKGROUND" VARCHAR2(20 BYTE) DEFAULT '未知', 
	"MAJOR" VARCHAR2(20 BYTE) DEFAULT '未知', 
	"ADDRESS" VARCHAR2(40 BYTE) DEFAULT '未知', 
	"COMPANY" VARCHAR2(40 BYTE) DEFAULT '未知' NOT NULL ENABLE, 
	"RELATION" VARCHAR2(20 BYTE) DEFAULT '无', 
	 CONSTRAINT "FRIEND_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
   COMMENT ON COLUMN "SCOTT"."FRIEND"."CREATEDATE" IS '创建时间';
   COMMENT ON COLUMN "SCOTT"."FRIEND"."HOBBY" IS '爱好';
   COMMENT ON COLUMN "SCOTT"."FRIEND"."SCHOOL" IS '学校';
   COMMENT ON COLUMN "SCOTT"."FRIEND"."EDUCATION_BACKGROUND" IS '教育背景';
   COMMENT ON COLUMN "SCOTT"."FRIEND"."MAJOR" IS '专业';
   COMMENT ON COLUMN "SCOTT"."FRIEND"."ADDRESS" IS '地址';
   COMMENT ON COLUMN "SCOTT"."FRIEND"."COMPANY" IS '公司';
   COMMENT ON COLUMN "SCOTT"."FRIEND"."RELATION" IS '关系';
